# Generated by Django 3.2.19 on 2023-12-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiegoPrueba',
            fields=[
                ('riegoid', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('automatico', models.BooleanField()),
            ],
        ),
    ]
